site_name: LCD Display Controller

theme:
  name: readthedocs

plugins:
  - mkdocstrings

nav:
  - Overview: index.md
  - LCD API: api.md
  - Source code: https://github.com/JamesRandom/i2c-lcd-controller
  - License: license.md