site_name: LCD Display Controller

theme:
  name: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          inventories:
          - https://docs.python.org/3/objects.inv
          # Include this option to document internal methods
          #options:
          #  filters: []

nav:
  - Overview: index.md
  - LCD API: api.md
  - Source code: https://github.com/JamesRandom/i2c-lcd-controller
  - License: license.md